name: Build

on:
  workflow_dispatch:
  push:
    tags: [REL-*]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Prepare virtualenv
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Build font binaries
        run: |
          . venv/bin/activate
          make clean && make all

      - name: Package Clavis
        uses: actions/upload-artifact@v6
        with:
          name: clavis
          path: out/clavis*

      - name: Package Gidotto
        uses: actions/upload-artifact@v6
        with:
          name: gidotto
          path: out/gidotto*


  Release:

    runs-on: ubuntu-latest
    needs: Build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Fetch build output
        uses: actions/download-artifact@v7

      - name: Prepare archives
        run: |
          cd clavis  && zip -r ../clavis-${{ github.ref_name }}.zip  * && cd ..
          cd gidotto && zip -r ../gidotto-${{ github.ref_name }}.zip * && cd ..

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ github.ref_name }}
          files: |
            clavis-${{ github.ref_name }}.zip
            gidotto-${{ github.ref_name }}.zip
